### ISSUE TITLE
Killswitch mode disables also proton API calls

### ISSUE THREAD

**Issue by falisca** [GenericMale/protonvpn-docker#33]
**Describe the bug**
If you enable the killswitch mode , using the "VPN_KILL_SWITCH=1" parameter, the applied iptables rules block everything including api.protonvnp.ch  calls that returns the servers list.
This way the container never goes into the ready state.

**To Reproduce**
Use the parameter "VPN_KILL_SWITCH=1" in docker command or in a compose file.
If you try to inspect the logs of the container you can see that the wget command, used to download the list of Proton servers, fails because blocked by iptables.

**Expected behavior**
The command to get servers list must be executed before the killswitch rules are applied, or make an exception for the ip/domain of protonvpn APIs.
Note that if you opt for the "domain exception" way, your ISP or any sniffers may know which vpn provider you are using or you may be vulnerable to dns attacks.

**hypothetical solution (domain exception way)**
In docker-entrypoint.sh convert the killsiwtchrules into iptables rules in a function, required because ip of Proton APIs could be changed in future.
Note that this is the "domain exception" way, so it couldn't be ideal for you.
new function:
`killswitch_vpn_setup() {
  # get ip of protonvpn APIs
  IP=$(nslookup $(echo $PROTON_API_URL | sed -e 's|https\?://||') | grep "Address" | tail -n 1 | awk '{print $2}')
    # use custom rules allowing ip of proton APIs
    # Flush all existing iptables rules
    iptables -F
    iptables -X

    # Set default policies to DROP for all incoming, outgoing, and forwarded traffic
    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT DROP

    # Allow loopback traffic (important for local services)
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A OUTPUT -o lo -j ACCEPT

    # Allow traffic through the VPN interface
    iptables -A INPUT -i tun+ -j ACCEPT
    iptables -A OUTPUT -o tun+ -j ACCEPT

    # Allow traffic from and to the local network (adjust as necessary)
    iptables -A INPUT -s 172.16.0.0/12 -i eth+ -j ACCEPT
    iptables -A OUTPUT -d 172.16.0.0/12 -o eth+ -j ACCEPT

    # Allow related and established connections (important for ongoing sessions)
    iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

    # allow only ip of Proton APIs
    iptables -A OUTPUT -d $IP -j ACCEPT
    iptables -A INPUT -s $IP -j ACCEPT
    log "Updated IP for $PROTON_API_URL: $IP"
}
`
Substitute the load of killswitch.rules file with the new function:
`    # iptables-restore /etc/iptables/killswitch.rules
    killswitch_vpn_setup
`
This is a proposal, I am open to fixes. :)

**Comment by GenericMale** [comment]
Thank you for the report but i can't reproduce the issue.

The [setup_split_tunnel](https://github.com/GenericMale/protonvpn-docker/blob/521340f1ad171aa8a4d5442ef66f12b2f5f4ea79/src/docker-entrypoint.sh#L44) function creates a special iptable rule to bypass the block for all calls made by "EXTERNAL_USER" and [run_as_external](https://github.com/GenericMale/protonvpn-docker/blob/521340f1ad171aa8a4d5442ef66f12b2f5f4ea79/src/docker-entrypoint.sh#L36C1-L36C16) is used to download the server list and certificates.

**Comment by RoyvanEmpel** [comment]
Hi, I'm also having troubles with the Killswitch. The container did work a few weeks ago without any problems. Could this possibly be the same issue?

My Docker compose:
```
services:
  protonvpn:
    image: genericmale/protonvpn
    restart: unless-stopped
    environment:
      - OPENVPN_USER_PASS_FILE=/run/secrets/protonvpn
      - VPN_RECONNECT=2:00
      - VPN_SERVER_COUNT=10
      - VPN_KILL_SWITCH=1
      - PROTON_TIER=2
    ports:
      - 8112:8112 # Deluge port
    volumes:
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    secrets:
      - protonvpn
secrets:
  protonvpn:
    file: /etc/protonvpn.auth
```

Log output:
![Image](https://github.com/user-attachments/assets/9f0623fe-2536-4b93-bb8d-9386b2c199cc)
