### ISSUE TITLE
Container unable to boot: can't fetch server list "401 Unauthorized"

### ISSUE THREAD

**Issue by RoyvanEmpel** [GenericMale/protonvpn-docker#34]
**Describe the bug**
When trying to run the container (which worked a few weeks ago) it never gets to a healthy state. It tries getting the server list which throws:
`wget: server returned error: HTTP/1.1 401 Unauthorized`

And then it tries to download certificates and throws:
`wget: server returned error: HTTP/1.1 400 Bad Request`

After this it still tries to connect but fails:
```
Connecting...
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: remote (2.6.11)
Use --help for more information.
Old IP: xx.xx.xx.xx
```
**To Reproduce**
Setup the container with the following compose. And try to start it (after adding the secret), it throws the wget errors on multiple devices on multiple networks for me.

**Expected behavior**
It beeing able to retrieve the server list and start a VPN connection.

**Docker Compose File**
```
services:
  protonvpn:
    image: genericmale/protonvpn
    restart: unless-stopped
    environment:
      - OPENVPN_USER_PASS_FILE=/run/secrets/protonvpn
      - VPN_RECONNECT=2:00
      - VPN_SERVER_COUNT=10
      - VPN_KILL_SWITCH=1
      - PROTON_TIER=2
    ports:
      - 8112:8112 # Deluge port
    volumes:
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    secrets:
      - protonvpn
secrets:
  protonvpn:
    file: /etc/protonvpn.auth
```

**Docker Logs**
```
Kill Switch enabled
Fetching Server List...
wget: server returned error: HTTP/1.1 401 Unauthorized
Downloading Certificates...
wget: server returned error: HTTP/1.1 400 Bad Request
Connecting...
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: remote (2.6.11)
Use --help for more information.
Old IP: xx.xx.xx.xx
```

**Environment (please complete the following information):**

- Docker Version: `24.0.5`
- Host OS: `Ubuntu 22.04.3`

**Additional context**
When going to the URL `https://api.protonvpn.ch/vpn/logicals` in your browser you also get a 401 saying "Invalid access token".
